site_name: Rhi's RoN Resources
site_description: Reign of Nightfall guides, tier lists, tools and resources

site_url: https://itsrhiana.github.io/rhi-ron-resources/

theme:
  name: material

  palette:
    scheme: slate

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.path
    - toc.follow

plugins:
  - search
  - macros

extra:
  site_base_path: /rhi-ron-resources

extra_css:
  - stylesheets/base.css
  - stylesheets/style-card.css
  - stylesheets/tier-list.css
  - stylesheets/style-page.css

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - javascripts/style-tabs.js

nav:
  - Home: index.md
  - Tier Lists: tier-lists/index.md
  - Styles: styles/index.md
  - Event Guides: events/index.md
  - Other Resources: guides/index.md